[package]
name = "state"
version = "0.3.3"
authors = ["Sergio Benitez <sb@sergio.bz>"]
description = """
A library for safe and effortless global and thread-local state management.
"""
documentation = "https://sergio.bz/rustdocs/state"
repository = "https://github.com/SergioBenitez/state"
readme = "README.md"
keywords = ["static", "tls", "state", "thread-local", "global"]
license = "MIT/Apache-2.0"

[features]
tls = ["thread_local"]
const_fn = []

[dependencies]
thread_local = { version = "0.3", optional = true }

[profile.release]
opt-level = 3
lto = true

[profile.bench]
opt-level = 3
lto = true

[package.metadata.docs.rs]
all-features = true
