[package]
name = "state"
version = "0.0.5"
authors = ["Sergio Benitez <sb@sergio.bz>"]
description = """
A library for safe and effortless global and thread-local state management.
"""
repository = "https://github.com/SergioBenitez/rust-state"
readme = "README.md"
keywords = ["global", "state", "thread-local", "tls", "static"]
license = "MIT/Apache-2.0"

[features]
tls = ["thread_local"]

[dependencies]
thread_local = { version = "0.3", optional = true }
